### ISSUE TITLE
Tracking master_me in package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [trummerschlunk/master_me#114]
Currently master_me is available in the following repos:

<a href="https://repology.org/project/master-me/versions">
    <img src="https://repology.org/badge/vertical-allrepos/master-me.svg?columns=3" alt="Packaging status">
</a>

Goal: make it available in the following repos:

- [ ] Alpine (linux)
- [ ] Chocolatey (windows) https://github.com/chocolatey-community/chocolatey-package-requests/issues/1441
- [ ] Debian (linux)
- [ ] Fedora (linux)
- [ ] FreeBSD 
- [ ] Gentoo (linux)
- [ ] Homebrew Cask (macOS binaries)
- [ ] OpenSUSE (linux)
- [ ] Ubuntu (linux)
- [ ] Winget (windows)
- [ ] Wikipedia (create a wikipedia page so a wikidata page is created)

**Comment by magnetophon** [comment]
It is also in NixOS: https://github.com/NixOS/nixpkgs/pull/226373

**Comment by trebmuh** [comment]
It is in LibraZiK4 as well, [since February 2023](https://mastodon.xyz/@LibraZiK/109845515841068351).

**Comment by luzpaz** [comment]
Added Chocolatey request

**Comment by danimo** [comment]
Not upstream but: https://build.opensuse.org/package/show/home:kill_it/master_me
