### ISSUE TITLE
Release task list

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#73]
A ticket to keep in mind a few things to do before release, not mentioned on other tickets as everything is pretty minor

- [x] Update screenshots (for readme) once final style and colors has been decided
- [x] Update README install instructions
- [x] Disable CLI print/preset export
- [x] Write about UI interaction in readme (shift+click to reset to default, ctrl+drag to go slower, double-click for text input)

**Comment by magnetophon** [comment]
I would add:
- [x] Update Block diagram in readme, possibly using the actual svg, or linking to it.

**Comment by trummerschlunk** [comment]
>     * [ ]  Update Block diagram in readme, possibly using the actual svg, or linking to it.

I uploaded the svg to img. Can this be directly linked in readme.md?

**Comment by magnetophon** [comment]
Yes, you can link an svg from the readme.

**Comment by magnetophon** [comment]
I think [dezippered gains](https://github.com/trummerschlunk/master_me/pull/77) are also mandatory for a mastering plugin!  ;)

**Comment by falkTX** [comment]
we forgot to close this one before, lets do that now
